Update config files, minify dist versions
OutreachInc/web-adstacks pull request #2
Opened 2023-03-14 21:43 UTC by ksquaredcoding

Updated all the gam-head files and synchronized file naming conventions. Removed deprecated code and minified all gam-head files for dist folder

2023-03-14 21:44 UTC, ksquaredcoding commented
![](https://github.trello.services/images/mini-trello-icon.png) [Update Prebid configuration for each website](https://trello.com/c/izq0ySl6/41-update-prebid-configuration-for-each-website)

2023-03-15 04:34 UTC, thechrise commented
It looks like we're missing Prebid in CL's gam-head.js file. Let's plan on adding that along with building out the ad slots in our advertising dashboards. We are missing a few opportunities throughout website configs.

2023-03-15 04:35 UTC, thechrise requested changes
It looks like we're missing Prebid in CL's gam-head.js file. Let's plan on adding that along with building out the ad slots in our advertising dashboards. We are missing a few opportunities throughout website configs.

2023-03-15 04:35 UTC, thechrise commented on foreverymom/index.html
> +    <script type="text/javascript" src="/AdController.js"></script>
@ksquaredcoding What is this AdController.js supposed to be? It looks like it's not included in the changes.

2023-03-17 17:30 UTC, merged